version: '3.4' 
services:
  dyndns:
    image: frankforpresident/transip-dyndns
    container_name: "transip-dynamic-dns"
    restart: always
    volumes:
      - ./data:/data
      - ~/.ssh/id_rsa.transip:/secrets/id_rsa.transip
